sudo: required

services:
  - docker

env:
  - RELEASE=1.7.1
  - RELEASE=1.7.1-couchperuser
  - RELEASE=2.1.2
  - RELEASE=dev
  - RELEASE=dev-cluster

script:
  - docker build -t couchdb:$RELEASE $RELEASE
  - docker run -d -p 5984:5984 couchdb:$RELEASE && sleep 10 && curl http://localhost:5984
